

fx_version 'cerulean'
games {  'gta5' }

description "RP module/framework"

dependency "ghmattimysql"
dependency "luna_mysql"

ui_page "gui/index.html"

shared_scripts {
  "sharedcfg/*",
  "cfg/cfg_blips.lua",
  "cfg/cfg_drugs.lua",
  "cfg/cfg_loginrewards.lua",
  "shared/*.lua",
  "cfg/cfg_settings.lua",
  "cfg/cfg_crosshair.lua",
  "cfg/weapons.lua"
}

-- RageUI
client_scripts {
	"rageui/RMenu.lua",
	"rageui/menu/RageUI.lua",
	"rageui/menu/Menu.lua",
	"rageui/menu/MenuController.lua",
	"rageui/components/*.lua",
	"rageui/menu/elements/*.lua",
	"rageui/menu/items/*.lua",
	"rageui/menu/panels/*.lua",
	"rageui/menu/panels/*.lua",
	"rageui/menu/windows/*.lua"
}

-- server scripts
server_scripts{ 
  "lib/utils.lua",
  "lib/Housingutils.lua",
  "base.lua",
  "modules/gui.lua",
  "modules/group.lua",
  "modules/admin.lua",
  "modules/survival.lua",
  "modules/player_state.lua",
  "modules/map.lua",
  "modules/money.lua",
  "modules/inventory.lua",
  "modules/settings_server.lua",
  "modules/sv_staffannounce.lua",
  "modules/identity.lua",
  "modules/police.lua",
  "modules/mission.lua",
  "modules/aptitude.lua",
  "modules/sv_emergencycalls.lua",
  "modules/sv_respawn.lua",
  "cfg/discordroles.lua",

  -- basic implementations
  "modules/basic_phone.lua",
  "modules/sv_nilperm.lua",
  "modules/basic_atm.lua",
  "modules/sv_gangblips.lua",
  "modules/sv_gangmenu.lua",
  "modules/basic_gunshop.lua",
  "modules/basic_garage.lua",
  "modules/basic_items.lua",
  "modules/basic_skinshop.lua",
  "modules/sv_policemenu.lua",
  "modules/sv_newplayer.lua",
  "modules/paycheck.lua",
  "modules/LsCustoms.lua",
  "modules/server_commands.lua",
  "modules/sv_playerlist.lua",
  "modules/warningsystem.lua",
  "modules/sv_cmds.lua",
  "modules/sv_dvsa.lua",
  "modules/sv_dealership.lua",
  "modules/sv_entitygun.lua",
  "modules/sv_dailyrewards.lua",
  "modules/panic_sv.lua",
  "modules/sv_tebex.lua",
  "modules/sv_adminmenu.lua",
  "modules/sv_moneydrops.lua",
  "modules/sv_inventory.lua",
  "modules/sv_phone.lua",
  "MergedServer/*",
  "modules/sv_announce.lua",
  "modules/sv_announcerestart.lua",
  "modules/sv_cardev.lua",
  "modules/sv_lunaclub.lua",
  "modules/sv_lunaanticheat.lua",
  "modules/sv_oldkillfeed.lua",
  "modules/sv_anticheat.lua",
  "modules/sv_gangfunds.lua",
  "modules/sv_speedgun.lua",
  "modules/sv_djmenu.lua",
  "modules/sv_drugs.lua",
  "modules/sv_callmanager.lua",
  "modules/sv_nhsmenu.lua",
  "modules/sv_blackjack.lua",
  "modules/sv_discordroles.lua",
  "modules/sv_tutorial.lua",
  "modules/sv_groupselector.lua",
  "modules/clothing.lua",
  "modules/sv_aamenu.lua",
  "modules/sv_casinochips.lua",
  "MergedServer/drugs/*.lua",
  "cfg/discordroles.lua",
  "LUNACore/server/*.lua"
}

-- client scripts
client_scripts{
  "lib/cl_thread.lua",
  "lib/cl_cache.lua",
  "lib/cl_util.lua",
  "cfg/atms.lua",
  "cfg/cfg_respawn.lua",
  "cfg/cfg_weapons.lua",
  "cfg/skinshops.lua",
  "cfg/garages.lua",
  "cfg/admin_menu.lua",
  "cfg/cfg_adminmenu.lua",
  "cfg/cfg_dvsa.lua",
  "client/cl_newplayer.lua",
  "cfg/gangfunds.lua",
  "lib/utils.lua",
  "lib/cl_mouse.lua",
  "client/Tunnel.lua",
  "client/cl_airbags.lua",
  "client/Proxy.lua",
  "client/base.lua",
  "client/cl_combattimer.lua",
  "client/cl_devmenu.lua",
  "client/cl_hideintrunk.lua",
  "client/cl_dynamicped.lua",
  "client/cl_lunaclub.lua",
  "client/cl_ui.lua",
  "client/cl_playerlist.lua",
  "utils/*",
  "client/iplloader.lua",
  "client/cl_announcerestart.lua",
  "client/cl_dvsa.lua",
  "client/cl_inventory.lua",
  "client/cl_announce.lua",
  "client/cl_policemenu.lua",
  "client/gui.lua",
  "client/player_state.lua",
  "client/survival.lua",
  "client/cl_loginrewards.lua",
  "client/map.lua",
  "client/cl_emergencycalls.lua",
  "client/cl_settings.lua",
  "client/cl_blackjack.lua",
  "client/cl_dailyrewards.lua",
  "client/identity.lua",
  "client/basic_garage.lua",
  "client/cl_oldkillfeed.lua",
  "client/cl_staffannounce.lua",
  "client/cl_crosshair.lua",
  "client/cl_anticheat.lua",
  "client/cl_lunaanticheat.lua",
  "client/cl_entitygun.lua",
  "client/cl_aamenu.lua",
  "client/police.lua",
  "client/cl_casinochips.lua",
  "client/cl_quests.lua",
  "client/cl_map.lua",
  "client/cl_cinameticbars.lua",
  "client/cl_weaponsback.lua",
  "client/cl_scope.lua",
  "client/cl_policehotkeys.lua",
  "client/lockcar-client.lua",
  "client/admin.lua",
  "client/cl_tutorial.lua",
  "client/cl_gangblips.lua",
  "client/enumerators.lua",
  "client/clothing.lua",
  "client/cl_moneydrop.lua",
  "client/atms.lua",
  "client/garages.lua",
  "client/panic_cl.lua",
  "client/cl_gangmenu.lua",
  "client/adminmenu.lua",
  "client/LsCustomsMenu.lua",
  "client/LsCustoms.lua",
  "client/warningsystem.lua",
  "client/cl_adminmenu.lua",
  "client/cl_nhsmenu.lua",
  "cl_pausmenu.lua",
  'client/cl_phone.lua',
  "MergedClient/*",
  "client/cl_cmds.lua",
  "client/cl_cardev.lua",
  "client/cl_gangfunds.lua",
  "client/cl_speedgun.lua",
  "client/cl_vehiclemenu.lua",
  "client/cl_vehiclewhitelist.lua",
  "client/cl_anpr.lua",
  "client/cl_delgun.lua",
  "client/cl_djmenu.lua",
  "client/cl_weaponsonback.lua",
  "client/cl_callmanager.lua",
  "MergedClient/drugs/*.lua",
  "client/cl_groupselector.lua",
  "LUNACore/client/*.lua"
}

-- client files
files{
  "peds.meta",
	'audio/dlcvinewood_amp.dat10',
	'audio/dlcvinewood_amp.dat10.nametable',
	'audio/dlcvinewood_amp.dat10.rel',
	'audio/dlcvinewood_game.dat151',
	'audio/dlcvinewood_game.dat151.nametable',
	'audio/dlcvinewood_game.dat151.rel',
	'audio/dlcvinewood_mix.dat15',
	'audio/dlcvinewood_mix.dat15.nametable',
	'audio/dlcvinewood_mix.dat15.rel',
	'audio/dlcvinewood_sounds.dat54',
	'audio/dlcvinewood_sounds.dat54.nametable',
	'audio/dlcvinewood_sounds.dat54.rel',
	'audio/dlcvinewood_speech.dat4',
	'audio/dlcvinewood_speech.dat4.nametable',
	'audio/dlcvinewood_speech.dat4.rel',
	'audio/sfx/dlc_vinewood/casino_general.awc',
	'audio/sfx/dlc_vinewood/casino_interior_stems.awc',
	'audio/sfx/dlc_vinewood/casino_slot_machines_01.awc',
	'audio/sfx/dlc_vinewood/casino_slot_machines_02.awc',
	'audio/sfx/dlc_vinewood/casino_slot_machines_03.awc',
	'audio/sfx/dlc_vinewood/*.awc',
  "lib/HousingTunnel.lua",
  "cfg/client.lua",
  "cfg/cfg_*.lua",
  "gui/index.html",
  "gui/design.css",
  "gui/index.css",
  "gui/main.js",
  "gui/index.js",
  "gui/Menu.js",
  "gui/ProgressBar.js",
  "gui/WPrompt.js",
  "gui/RequestManager.js",
  "gui/AnnounceManager.js",
  "gui/Div.js",
  "gui/dynamic_classes.js",
  "gui/fonts/Pdown.woff",
  "gui/fonts/GTA.woff",
  "gui/img/death.png",
   "gui/killfeed/img/*.png",
  "gui/killfeed/font/stratum2-bold-webfont.woff",
  "gui/killfeed/index.js",
  "gui/killfeed/style.css",
  "gui/money/img/*.png",
  "gui/money/index.css",
  "gui/money/index.js",
  "gui/playerlist_images/*.png",
  'gui/sounds/*',
  "gui/SoundManager.js",
}

data_file "PED_METADATA_FILE" "peds.meta"

data_file 'AUDIO_GAMEDATA' 'audio/dlcvinewood_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/dlcvinewood_sounds.dat'
data_file 'AUDIO_DYNAMIXDATA' 'audio/dlcvinewood_mix.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/dlcVinewood_amp.dat'
data_file 'AUDIO_SPEECHDATA' 'audio/dlcvinewood_speech.dat'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_vinewood'